- Infrastructure:
    - Pi-hole:
        icon: pi-hole
        href: http://scooby:8080/admin
        description: Network Guardian
        widget:
          type: pihole
          version: 6
          url: http://pihole:80
          key: 'YIDyzdyUoAghA9m0jcPMcgJD2qg12Qlu98MHlZg+VK4='
    - Portainer:
        icon: portainer
        href: https://localhost:9443
        description: Docker Management

- Services:
    - Uptime Kuma:
        icon: uptime-kuma
        href: http://localhost:3001
        widget:
          type: uptimekuma
          url: http://uptime-kuma:3001
    - Jellyfin:
        icon: jellyfin
        href: http://localhost:8096
        description: Media Server
    - n8n:
        icon: n8n
        href: http://localhost:5678
        description: Automations
    - Portfolio:
        icon: nginx
        href: http://localhost:8081
        description: Local Dev Site
