- Infrastructure:
    - Node Health:
        - Pi-hole:
            icon: pi-hole
            href: http://scooby:8082/admin
            description: Network Guardian
            widget:
              type: pihole
              version: 6
              url: http://pihole:80
              key: '{{HOMEPAGE_VAR_PIHOLE_KEY}}'

        - Portainer:
            icon: portainer
            href: https://scooby:9443
            description: Docker Management
            widget:
              type: portainer
              url: http://portainer:9000
              env: 3
              key: '{{HOMEPAGE_VAR_PORTAINER_API_KEY}}'
              fields: ["running", "stopped", "total"]

        - Docker:
            icon: docker
            description: Container Health
            widget:
              type: docker
              server: my-docker
              container: homepage

- Media & Apps:
    - Streaming:
        - Jellyfin:
            icon: jellyfin
            href: http://scooby:8096
            description: Media Server
            widget:
              type: jellyfin
              url: http://jellyfin:8096
              key: '{{HOMEPAGE_VAR_JELLYFIN_API_KEY}}'
              enableNowPlaying: true

    - Monitoring:
        - Portfolio:
            icon: nextjs
            href: https://dharmikshinde.tech
            description: Personal Site

- Quick Links:
    - GitHub:
        icon: github
        href: https://github.com/
    - Reddit:
        icon: reddit
        href: https://reddit.com/
    - YouTube:
        icon: youtube
        href: https://youtube.com/
    - Gmail:
        icon: gmail
        href: https://mail.google.com/
